apiVersion: v1
kind: Namespace
metadata:
  name: secure-namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: limited-sa
  namespace: secure-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: secure-namespace
  name: pod-reader
rules:
- apiGroups: [""] # core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: secure-namespace
subjects:
- kind: ServiceAccount
  name: limited-sa
  apiGroup: ""
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io